app/routes/post.py
from flask import Blueprint,render_template,request, redirect,abort
from flask_login import login_required,current_user
from ..extensions import db
from sqlalchemy import desc
from ..models.post import Post
from ..models.user import User
from ..forms import PostForm, StudentForm, TeacherForm
post = Blueprint('post', __name__)

@post.route('/', methods = ['POST', 'GET'])
def all():
    form = TeacherForm()
    form.teacher.choices = [t.name for t in User.query.filter_by(status='teacher')]
    if form.validate_on_submit():
        teacher = form.teacher.data
        teacher_id = User.query.filter_by(name=teacher).first().id
        posts = Post.query.filter_by(teacher=teacher_id).order_by(Post.date.desc()).all()
    elif "orderby" in request.args:
        posts = Post.query.order_by(request.args["orderby"]).all() 
        #Post.query.order_by(Post.date.desc()).all()
    else:
        posts = Post.query.order_by(desc("date")).limit(20).all()
    return render_template('post/all.html', posts=posts, user=User, form=form)


@post.route('/post/create', methods = ['POST','GET'])
@login_required
def create():
    form = PostForm()
    studentForm = StudentForm()
    studentForm.student.choices = [s.name for s in User.query.filter_by(status='user')]
    if form.validate_on_submit():
        student_id = User.query.filter_by(name=studentForm.student.data).first().id
        post = Post(teacher=current_user.id,
                    subject=form.subject.data,
                    student=student_id)
        
        try:
            db.session.add(post)
            db.session.commit()
            return redirect('/')
        except Exception as e:
            print(str(e))

    return render_template('post/create.html',form=form, studentForm=studentForm)


@post.route('/post/<int:id>/update', methods = ['POST','GET'])
@login_required
def update(id):
    post = Post.query.get(id)
    if post.author.id == current_user.id:
        form = PostForm()
        studentForm = StudentForm()
        
        studentForm.student.choices = [s.name for s in User.query.filter_by(status='user')]
        if form.validate_on_submit():
            post.subject = form.subject.data
            post.likes = 0
            student_id = User.query.filter_by(name=studentForm.student.data).first().id
            post.student = student_id
            try:
                db.session.commit()
                return redirect('/')
            except Exception as e:
                print(str(e))
        else:
            student = User.query.filter_by(id=post.student).first()
            studentForm.student.data = student.name
            form.subject.data = post.subject
            return render_template('post/update.html', post=post, form=form,studentForm=studentForm)
    else:
        abort(403)


@post.route('/post/<int:id>/delete', methods = ['POST','GET'])
@login_required
def delete(id):

    post = Post.query.get(id)
    if post.author.id == current_user.id:
        if request.method == 'POST':
            try:
                db.session.delete(post)
                db.session.commit()
            except Exception as e:
                print(str(e))
                return str(e)
            return redirect('/')
        else:
            return render_template('post/delete.html', post=post)
    else:
        abort(403)
    

@post.route('/post/<int:id>/like', methods = ['GET'])
@login_required
def like(id):
    post = Post.query.get(id)
    if post.likes is None:
        post.likes = 0
    else:
        post.likes += 1
    try:
        db.session.commit()
    except Exception as e:
        print(str(e))
        return str(e)
    return redirect("/")


@post.route('/post/<int:id>/dislike', methods = ['GET'])
@login_required
def dislike(id):
    post = Post.query.get(id)
    if post.likes is None:
        post.likes = 0
    else:
        post.likes -= 1
    try:
        db.session.commit()
    except Exception as e:
        print(str(e))
        return str(e)
    return redirect("/")

app/routes/user.py
from flask import Blueprint, render_template, redirect, request, flash, current_app,url_for
from ..extensions import db,bcrypt
from ..models.user import User
from ..forms import RegistrationForm, LoginForm
from ..functions import save_picture
from ..config import Config
from flask_login import login_user,logout_user
user = Blueprint('user', __name__)

@user.route('/user/register', methods= ['GET','POST'])
def register():
    form = RegistrationForm()
    
    if form.validate_on_submit():
        #current_app.config['SECRET_KEY']
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        filename = save_picture(form.avatar.data)

        user = User(name=form.name.data, login=form.login.data, avatar=filename, password=hashed_password)
        try:
            db.session.add(user)
            db.session.commit()
            flash(f"Поздравляем, {form.login.data} вы успешно зарегестрированы!", "success")
            return redirect(url_for("user.login"))
        except Exception as e:
            print(str(e))
            flash(f"При регистрации произошла ошибка, ", "danger")
    return render_template("user/register.html", form=form)

@user.route('/user/login', methods= ['GET','POST'])
def login():
    form = LoginForm()
    
    if form.validate_on_submit():
        user = User.query.filter_by(login=form.login.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            flash(f"Поздравляем, {form.login.data} вы успешно авторизованны!", "success")
            return redirect(next_page) if next_page else redirect(url_for('post.all'))
        else:
            flash("Неверные данные входа", "danger")
    return render_template("user/login.html", form=form)

@user.route('/user/logout', methods=['POST', 'GET'])
def logout():
    logout_user()
    return redirect(url_for("post.all"))

app/templates/main/_flash.html
<!-- FLASH MESSAGES-->
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
    {% for category, message in messages %}
        <div class="alert alert-{{category}}">
            {{message}}
        </div>
    {% endfor %}
{% endif %}
{% endwith %}
<!-- FLASH MESSAGES-->

app/templates/main/_footer.html
<ul class="nav justify-content-center border-bottom pb-3 mb-3">
    <li class="nav-item"><a href="#" class="nav-link px-2">Home</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2">Features</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2">Pricing</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2">FAQs</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2">About</a></li>
</ul>
<p class="text-center">© 2024 Company, Inc</p>

app/templates/main/_header.html
<div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
    <a href="{{url_for('post.all')}}" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
        <img class = "header_img" src="{{ url_for('static', filename='img/sample.png')}}" alt="sample">
    </a>

    <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
      <li><a href="{{url_for('post.all')}}" class="nav-link px-2 text-secondary">Главная</a></li>
      {% if current_user.is_authenticated and current_user.status == 'teacher' %}
      <li><a href="{{url_for('post.create')}}" class="nav-link px-2 text-white">Добавить тему</a></li>
      {%endif%}
      <li><a href="#" class="nav-link px-2 text-white">Pricing</a></li>
      <li><a href="#" class="nav-link px-2 text-white">FAQs</a></li>
      <li><a href="#" class="nav-link px-2 text-white">About</a></li>
    </ul>

    <div class="text-end">
      {% if current_user.is_authenticated %}
      <span>Добро пожаловать {{current_user.login}}</span>
      <a href="{{url_for('user.logout')}}" class="btn btn-outline-light me-2">Выйти</a>
      {% else %}
      <a href="{{url_for('user.login')}}" class="btn btn-outline-light me-2">Авторизация</a>
      {%endif%}
      <a href="{{url_for('user.register')}}" class="btn btn-warning">Регистрация</a>
    </div>
</div>

app/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{url_for('static', filename='css/libs/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/main.css')}}">
    {% block style %} {% endblock%}
    <title>{% block title%}{% endblock %}</title>
    
</head>
<body>    
<div class="page">
    <header class="header">{% include 'main/_header.html' %}</header>
    

    <main class="content">
        {% include 'main/_flash.html' %}
        <h1>{{self.title()}}</h1>
        {% block content%}{% endblock %}
    </main>
    
    <footer class="py-3 my-4">{% include 'main/_footer.html' %}</footer>
</div>
    
    <script src="{{url_for('static', filename='js/libs/bootstrap.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/app.js')}}"></script>
    {%block script %} {%endblock%}
</body>
</html>