app/models/post.py
from ..extensions import db
from datetime import datetime
class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    teacher = db.Column(db.Integer, db.ForeignKey('user.id', ondelete="CASCADE"))
    student = db.Column(db.Integer)
    subject = db.Column(db.String(250))
    body = db.Column(db.String(500))
    date = db.Column(db.DateTime, default=datetime.now)
    likes = db.Column(db.Integer, default=0)

app/routes/post.py
from flask import Blueprint,render_template,request, redirect,abort
from flask_login import login_required,current_user
from ..extensions import db
from sqlalchemy import desc
from ..models.post import Post
from ..models.user import User
from ..forms import PostForm, StudentForm, TeacherForm
post = Blueprint('post', __name__)

@post.route('/', methods = ['POST', 'GET'])
def all():
    form = TeacherForm()
    form.teacher.choices = [t.name for t in User.query.filter_by(status='teacher')]
    if form.validate_on_submit():
        teacher = form.teacher.data
        teacher_id = User.query.filter_by(name=teacher).first().id
        posts = Post.query.filter_by(teacher=teacher_id).order_by(Post.date.desc()).all()
    elif "orderby" in request.args:
        posts = Post.query.order_by(request.args["orderby"]).all() 
        #Post.query.order_by(Post.date.desc()).all()
    else:
        posts = Post.query.order_by(desc("date")).limit(20).all()
    return render_template('post/all.html', posts=posts, user=User, form=form)


@post.route('/post/create', methods = ['POST','GET'])
@login_required
def create():
    form = PostForm()
    studentForm = StudentForm()
    studentForm.student.choices = [s.name for s in User.query.filter_by(status='user')]
    if form.validate_on_submit():
        student_id = User.query.filter_by(name=studentForm.student.data).first().id
        post = Post(teacher=current_user.id,
                    subject=form.subject.data,
                    student=student_id)
        
        try:
            db.session.add(post)
            db.session.commit()
            return redirect('/')
        except Exception as e:
            print(str(e))

    return render_template('post/create.html',form=form, studentForm=studentForm)


@post.route('/post/<int:id>/update', methods = ['POST','GET'])
@login_required
def update(id):
    post = Post.query.get(id)
    if post.author.id == current_user.id:
        form = PostForm()
        studentForm = StudentForm()
        
        studentForm.student.choices = [s.name for s in User.query.filter_by(status='user')]
        if form.validate_on_submit():
            post.subject = form.subject.data
            post.likes = 0
            student_id = User.query.filter_by(name=studentForm.student.data).first().id
            post.student = student_id
            try:
                db.session.commit()
                return redirect('/')
            except Exception as e:
                print(str(e))
        else:
            student = User.query.filter_by(id=post.student).first()
            studentForm.student.data = student.name
            form.subject.data = post.subject
            return render_template('post/update.html', post=post, form=form,studentForm=studentForm)
    else:
        abort(403)


@post.route('/post/<int:id>/delete', methods = ['POST','GET'])
@login_required
def delete(id):

    post = Post.query.get(id)
    if post.author.id == current_user.id:
        if request.method == 'POST':
            try:
                db.session.delete(post)
                db.session.commit()
            except Exception as e:
                print(str(e))
                return str(e)
            return redirect('/')
        else:
            return render_template('post/delete.html', post=post)
    else:
        abort(403)
    

@post.route('/post/<int:id>/like', methods = ['GET'])
@login_required
def like(id):
    post = Post.query.get(id)
    if post.likes is None:
        post.likes = 0
    else:
        post.likes += 1
    try:
        db.session.commit()
    except Exception as e:
        print(str(e))
        return str(e)
    return redirect("/")


@post.route('/post/<int:id>/dislike', methods = ['GET'])
@login_required
def dislike(id):
    post = Post.query.get(id)
    if post.likes is None:
        post.likes = 0
    else:
        post.likes -= 1
    try:
        db.session.commit()
    except Exception as e:
        print(str(e))
        return str(e)
    return redirect("/")

app/templates/post/all.html
{% extends 'main/base.html'%}
{%block title %} Все темы {% endblock %}
{%block style %} 
    {% assets 'post_all_css' %}
        <link rel="stylesheet" href="{{ASSET_URL}}">
    {% endassets %}
{% endblock %}


{%block content %}

<form method="post" class="form-control d-flex flex-row gap-2" id="teacherForm">
    {{form.csrf_token }}
    {{form.teacher }}
    <input type="submit" class="btn btn-success" value="показать">
</form>

<div class="table-responsive custom-table-responsive">
    <table class="table custom-table">

        <thead>
            <tr>
                <th scope="col">
                    <a href="{{url_for('post.all',orderby='teacher')}}">Преподаватель</a>
                </th>
                <th scope="col">
                    <a href="{{url_for('post.all',orderby='subject')}}">Тема</a>
                </th>
                <th scope="col">
                    <a href="{{url_for('post.all',orderby='student')}}">ФИО студента</a>
                </th>
                {% if current_user.is_authenticated %}
                <th scope="col">действие
                </th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for post in posts%}
            <tr scope="row">
                <td>
                    <img width="46px" height="46px" src="{{url_for('static', filename='upload/'+ post.author.avatar)}}" alt="Преподаватель">
                    {{post.author.name}}
                </td>
                <td>{{post.subject}}
                </td>
                <td>
                    {% with student=user.query.get(post.student) %}
                    <img width="46px" height="46px" src="{{url_for('static', filename='upload/'+ student.avatar)}}" alt="Студент">
                     {{ student.name }}
                    {% endwith %}
                </td>
                
                <td>
                    {% if current_user.is_authenticated and post.author.id == current_user.id %}
                    <a href="{{url_for('post.update',id=post.id)}}" class="btn btn-sm btn-primary">Ред.</a>
                    <a href="{{url_for('post.delete',id=post.id)}}" class="btn btn-sm btn-danger">Удалить</a>
                    <a href="{{url_for('post.like',id=post.id)}}" class="btn btn-sm btn-success">Like 
                        
                        {% if post.likes > 0 %}
                            {{post.likes}}
                        {% endif%}
                    </a>
                    <a href="{{url_for('post.dislike',id=post.id)}}" class="btn btn-sm btn-secondary">Diz
                        {% if post.likes < 0 %}
                            {{(-1) * post.likes}}
                        {% endif%}
                    </a>
                    {% endif  %}
                </td>
                
            </tr>
            {% endfor %}
        </tbody> 
    </table>
</div>
{% endblock %}

{%block script %} 
    {% assets 'post_all_js' %}
    <script  type="text/javascript" src="{{ASSET_URL}}"> </script>
    {% endassets %}
{% endblock %}

app/templates/post/create.html
{% extends 'main/base.html'%}
{%block title %} добавление темы {% endblock %}
{% block content %}
<form method="post" class="form-control d-flex flex-column gap-2">
    {{form.csrf_token}}
    {{form.subject(class="form-control", placeholder="Тема")}}    
    {{studentForm.student}}
    {{form.submit(class="btn btn-success")}}
</form>


{% endblock %}

app/templates/post/delete.html
{% extends 'main/base.html'%}
{%block title %} удаление темы {{post.id}}{% endblock %}
{% block content %}
<form method="post" class="form-control d-flex flex-column gap-2">
    <input value="Вы действительно хотите удалить тему {{post.subject}}" type="submit" class="btn btn-danger">
</form>
<a href="{{url_for('post.all')}}" class="btn btn-sm btn-secondary">Назад</a>
{% endblock %}

app/templates/post/update.html
{% extends 'main/base.html'%}
{%block title %} редактивроания темы "{{post.subject}}" {% endblock %}
{% block content %}
<form method="post" class="form-control d-flex flex-column gap-2">
    {{form.csrf_token}}
    <div class="d-flex flex-row gap-5 ">
        <div >
        Автор</div>
        <div class="flex-grow-1"> {{post.author.name}} </div>  
    </div>
    <div class="d-flex flex-row gap-1 justify-content-start">
        {{form.subject.label}} 
        <div class="flex-grow-1">{{form.subject(class="form-control", placeholder="Тема")}}</div> 
    </div>
    <div class="d-flex flex-row gap-1 justify-content-start">
        {{studentForm.student.label}} 
        <div class="flex-grow-1">{{studentForm.student(class="form-control", placeholder="ФИО студента")}}</div> 
    </div>
    {{form.submit(class="btn btn-success")}}
</form>

{% endblock %}